import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { unstable_startWorker } from 'wrangler';
import { chromium } from '@playwright/test';
const origin = 'http://127.0.0.1:8795';
const out = 'artifacts/editor-navigation';
await mkdir(out, { recursive: true });
const state = `${out}/state-${Date.now()}`;
execFileSync(process.execPath, ['node_modules/wrangler/bin/wrangler.js', 'd1', 'migrations', 'apply', 'web-radar', '--local', '--env', 'test', '--persist-to', state], { stdio: 'pipe' });
let worker, browser;
try {
  worker = await unstable_startWorker({ config: 'wrangler.jsonc', env: 'test', dev: { server: { hostname: '127.0.0.1', port: 8795 }, persist: state, inspector: false, watch: false, logLevel: 'error' } });
  await worker.ready;
  browser = await chromium.launch({ headless: true, executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  assert.equal((await context.request.post(origin + '/api/auth/test-login', { data: { identity: 'owner' } })).status(), 200);
  const created = await context.request.post(origin + '/api/projects', { data: { name: 'Navigation verification', buildBranch: 'template', requestId: crypto.randomUUID() } });
  const project = (await created.json()).project;
  assert.ok(project?.id);
  const page = await context.newPage(), errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${origin}/?view=projects&project=${project.id}&tab=template`);
  const previews = page.getByRole('button', { name: /^预览 / });
  await previews.first().waitFor();
  await previews.first().click();
  await page.locator('.preview-overlay iframe').waitFor();
  await page.getByRole('button', { name: '返回选择模板', exact: true }).click();
  await page.locator('.preview-overlay').waitFor({ state: 'detached' });
  assert.equal(new URL(page.url()).searchParams.get('tab'), 'template');
  await previews.first().click();
  await page.locator('.preview-overlay iframe').waitFor();
  await page.getByLabel('预览页面').selectOption('catalog');
  await page.locator('.preview-overlay iframe').waitFor();
  await page.goBack();
  await page.locator('.preview-overlay').waitFor({ state: 'detached' });
  await previews.first().waitFor();
  await page.goForward();
  await page.getByRole('button', { name: '返回选择模板', exact: true }).waitFor();
  await page.getByLabel('关闭预览').click();
  await page.locator('.preview-overlay').waitFor({ state: 'detached' });
  await previews.first().click();
  await page.locator('.preview-overlay iframe').waitFor();
  await page.screenshot({ path: `${out}/preview-desktop.png` });
  await page.setViewportSize({ width: 390, height: 844 });
  const back = page.getByRole('button', { name: '返回选择模板', exact: true });
  assert.ok(await back.isVisible());
  const rect = await back.boundingBox();
  assert.ok(rect.x >= 0 && rect.x + rect.width <= 390);
  await page.screenshot({ path: `${out}/preview-mobile.png` });
  await back.click();
  await page.locator('.preview-overlay').waitFor({ state: 'detached' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.getByRole('link', { name: 'Web Radar · 返回控制台首页' }).click();
  await page.getByRole('heading', { name: '控制台', exact: true }).waitFor();
  assert.equal(new URL(page.url()).searchParams.has('project'), false);
  assert.equal(new URL(page.url()).searchParams.has('tab'), false);
  assert.equal(new URL(page.url()).searchParams.has('view'), false);
  assert.equal(await page.evaluate(() => history.state?.wrPreview), undefined);
  // A failed save must not turn the home link into silent data loss.
  await page.goto(`${origin}/?view=projects&project=${project.id}&tab=basics`);
  await page.getByLabel('公司 / 品牌名称', { exact: true }).waitFor();
  await page.route(`**/api/projects/${project.id}`, route => route.request().method() === 'PUT' ? route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Save unavailable for navigation test' } }) }) : route.continue());
  await page.getByLabel('公司 / 品牌名称', { exact: true }).fill('Unsaved navigation change');
  await page.getByRole('link', { name: 'Web Radar · 返回控制台首页' }).click();
  await page.getByRole('button', { name: '继续编辑', exact: true }).click();
  assert.equal(await page.getByLabel('公司 / 品牌名称', { exact: true }).inputValue(), 'Unsaved navigation change');
  await page.getByRole('link', { name: 'Web Radar · 返回控制台首页' }).click();
  await page.getByRole('button', { name: '放弃修改并返回', exact: true }).click();
  await page.getByRole('heading', { name: '控制台', exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: preview Back/Forward, explicit return, close, mobile toolbar, logo home, URL cleanup, unsaved-change guard, no browser errors.');
} finally {
  await browser?.close();
  await worker?.dispose();
}
