import { useEffect, useState } from 'react';
import { api, put, errorMessage } from './api';
import { Button, Empty, Field, Icon, Modal, Notice, dateTime } from './components';
import { roleLabels, roleDescriptions, type AppRole } from '../shared/access';
import type { Principal } from '../shared/model';
export type Member = {workspace_id:string;user_id:string;email:string;display_name:string;workspace_name:string;upstream_role:string;is_super:number;role:AppRole|null;status:string;version:number;created_at:string;last_seen_at:string|null;projects:number;drafts:number;published:number;campaigns:number;sent:number;replied:number;messages:number};
type Directory = {members:Member[];total:number;page:number;pageSize:number;canManage:boolean};
type RecordRow = {id:string;name:string;status:string;createdAt:string|number;workspaceId:string;creatorId:string|null;creatorName:string|null;creatorEmail:string|null;senderEmail?:string;totalSent?:number;totalRecipients?:number;totalDelivered?:number;totalOpened?:number;totalClicked?:number;totalReplied?:number;totalTargets?:number;totalSubmitted?:number;totalFailed?:number};
const names:Record<string,string>={draft:'草稿',published:'已发布',offline:'已下线',scheduled:'定时发送',sending:'发送中',completed:'已完成',failed:'失败',paused:'已暂停',queued:'排队中',running:'执行中',needs_review:'待核对'};
export default function UserManagement({principal,section,initialMember,onViewData}:{principal:Principal;section:'users'|'business';initialMember?:Member|null;onViewData?:(member:Member)=>void}) {
  const business=section==='business';
  const [tab,setTab]=useState<'members'|'projects'|'campaigns'|'messages'|'audit'>(business&&initialMember?'projects':'members');
  const [directory,setDirectory]=useState<Directory|null>(null),[records,setRecords]=useState<{records:RecordRow[];total:number}|null>(null);
  const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[filter,setFilter]=useState<Member|null>(initialMember||null),[legacy,setLegacy]=useState(false);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  const [edit,setEdit]=useState<Member|null>(null),[role,setRole]=useState<AppRole>('member'),[status,setStatus]=useState('active');
  const [audit,setAudit]=useState<any[]>([]),[detail,setDetail]=useState<any|null>(null);
  useEffect(()=>{let active=true;setBusy(true);setError('');
    const params=new URLSearchParams({page:String(page),search:query});
    const load=tab==='members'?api<Directory>('/api/management/members?'+params).then(v=>{if(active)setDirectory(v)}):tab==='audit'?api<{events:any[]}>('/api/management/audit').then(v=>{if(active)setAudit(v.events)}):api<{records:RecordRow[];total:number}>('/api/management/records?'+new URLSearchParams({kind:tab,page:String(page),...(filter?{workspaceId:filter.workspace_id,userId:filter.user_id}:{}),...(legacy?{userId:'__legacy__'}:{})})).then(v=>{if(active)setRecords(v)});
    load.catch(e=>{if(active)setError(errorMessage(e))}).finally(()=>{if(active)setBusy(false)});return()=>{active=false};
  },[tab,page,query,filter,legacy,revision]);
  const switchTab=(next:typeof tab)=>{setTab(next);setPage(1);setRecords(null)};
  async function save(){if(!edit)return;setBusy(true);setError('');try{await put('/api/management/members',{workspaceId:edit.workspace_id,userId:edit.user_id,version:edit.version,role,status});setEdit(null);setRevision(v=>v+1)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}}
  const total=tab==='members'?directory?.total||0:records?.total||0;
  return <div className="user-management">
    <div className="page-heading"><h1>{business?'业务数据':'用户管理'}</h1><p>{business?'按用户查看网站、邮件活动与站内信的统计和明细。':'管理账号角色、访问状态与权限操作记录。'}{principal.systemRole==='super_admin'?'当前范围：全平台。':'当前范围：所在工作区。'}</p></div>
    {error&&<Notice tone="error">{error}</Notice>}
    <nav className="management-tabs" aria-label={business?'业务数据分类':'用户管理功能'}>{((business?[['members','用户汇总'],['projects','网站项目'],['campaigns','EDM 邮件'],['messages','站内信']]:[['members','用户列表'],['audit','权限操作记录']]) as [typeof tab,string][]).map(([id,label])=><Button key={id} kind={tab===id?'primary':'secondary'} onClick={()=>switchTab(id)}>{label}</Button>)}</nav>
    {tab==='members'?<>
      {!business&&<section className="panel"><h2>角色权限</h2><div className="management-role-grid">{Object.entries(roleDescriptions).map(([id,text])=><div key={id}><strong>{roleLabels[id as AppRole]}</strong><p className="muted">{text}</p></div>)}</div><p className="muted">超级管理员由统一账号服务管理。账号首次登录后自动加入用户列表；已有网站的创建者也会列出，姓名和邮箱将在登录后补齐。此处停用只影响 Web Radar。</p></section>}
      <section className="panel"><form className="management-filters" onSubmit={e=>{e.preventDefault();setPage(1);setQuery(search)}}><input aria-label="搜索用户" placeholder="姓名、邮箱或用户 ID" value={search} onChange={e=>setSearch(e.target.value)}/><Button type="submit">搜索</Button><Button onClick={()=>setRevision(v=>v+1)}><Icon name="refresh"/>刷新</Button></form>
      <div className="table-scroll"><table><thead><tr><th>用户 / 工作区</th>{business?<><th>网站：创建 / 草稿 / 已发布</th><th>邮件：活动 / 已发 / 回复</th><th>站内信任务</th></>:<><th>角色 / 状态</th><th>加入 / 最近访问</th></>}<th>操作</th></tr></thead><tbody>{directory?.members.map(m=><tr key={m.workspace_id+':'+m.user_id}><td><strong>{m.display_name||m.user_id}</strong><small>{m.email||'待登录补齐邮箱'}</small><small>{m.workspace_name||m.workspace_id}</small></td>{business?<><td>{m.projects} / {m.drafts} / {m.published}</td><td>{m.campaigns} / {m.sent} / {m.replied}</td><td>{m.messages}</td></>:<><td>{roleLabels[m.is_super?'super_admin':m.role||(m.upstream_role==='admin'?'admin':'member')]}<small>{m.status==='disabled'?'已停用':'正常'}</small></td><td>{dateTime(m.created_at)}<small>{m.last_seen_at?dateTime(m.last_seen_at):'尚未记录访问'}</small></td></>}<td><Button onClick={()=>{if(!business){onViewData?.(m);return;}setFilter(m);setLegacy(false);switchTab('projects')}}>查看业务数据</Button>{!business&&directory?.canManage&&!m.is_super&&m.user_id!==principal.userId&&<Button onClick={()=>{setEdit(m);setRole(m.role||(m.upstream_role==='admin'?'admin':'member'));setStatus(m.status)}}>权限设置</Button>}</td></tr>)}</tbody></table></div></section>
    </>:tab==='audit'?<section className="panel"><h2>最近 100 条权限操作</h2><div className="table-scroll"><table><thead><tr><th>时间</th><th>操作人</th><th>目标用户</th><th>变更</th></tr></thead><tbody>{audit.map(e=><tr key={e.id}><td>{dateTime(e.created_at)}</td><td>{e.actor_id}</td><td>{e.target_id}</td><td><code>{e.detail}</code></td></tr>)}</tbody></table></div></section>:<section className="panel">
      <div className="management-filters"><strong>{legacy?'历史共享数据':filter?`创建者：${filter.display_name||filter.email||filter.user_id}`:'全部可见用户'}</strong>{filter&&<Button onClick={()=>{setFilter(null);setPage(1)}}>清除用户筛选</Button>}{tab!=='projects'&&<label><input type="checkbox" checked={legacy} onChange={e=>{setLegacy(e.target.checked);setPage(1)}}/>只看历史共享数据</label>}<Button onClick={()=>setRevision(v=>v+1)}><Icon name="refresh"/>刷新</Button></div>
      {tab!=='projects'&&<p className="muted">旧版数据仅记录工作区，无法确认创建者，显示为“历史共享数据”。邮件数据来自本系统发送记录；回复需接入收件邮箱，未接入不代表没有收到回复。</p>}
      <div className="table-scroll"><table><thead><tr><th>名称</th><th>创建者</th><th>创建时间</th><th>状态</th><th>{tab==='campaigns'?'收件人 / 已发送 / 送达 / 打开 / 点击 / 回复':tab==='messages'?'目标网站 / 成功 / 失败':'项目 ID'}</th>{tab!=='projects'&&<th>明细</th>}</tr></thead><tbody>{records?.records.map(r=><tr key={r.id}><td><strong>{r.name}</strong>{r.senderEmail&&<small>{r.senderEmail}</small>}</td><td>{r.creatorName||r.creatorEmail||r.creatorId||'历史共享数据'}</td><td>{dateTime(typeof r.createdAt==='number'?new Date(r.createdAt).toISOString():r.createdAt)}</td><td>{names[r.status]||r.status}</td><td>{tab==='campaigns'?`${r.totalRecipients} / ${r.totalSent} / ${r.totalDelivered} / ${r.totalOpened} / ${r.totalClicked} / ${r.totalReplied}`:tab==='messages'?`${r.totalTargets} / ${r.totalSubmitted} / ${r.totalFailed}`:r.id}</td>{tab!=='projects'&&<td><Button onClick={async()=>{try{setDetail(await api('/api/management/records/'+tab+'/'+encodeURIComponent(r.id)))}catch(e){setError(errorMessage(e))}}}>查看明细</Button></td>}</tr>)}</tbody></table></div>
      {!busy&&records?.records.length===0&&<Empty title="暂无符合条件的数据"/>}</section>}
    {busy&&<p role="status">正在读取…</p>}{tab!=='audit'&&<div className="management-filters"><span>共 {total} 条 · 第 {page} 页</span><Button disabled={page===1||busy} onClick={()=>setPage(p=>p-1)}>上一页</Button><Button disabled={page*50>=total||busy} onClick={()=>setPage(p=>p+1)}>下一页</Button></div>}
    {edit&&<Modal title={'权限设置 · '+(edit.display_name||edit.email||edit.user_id)} onClose={()=>setEdit(null)}><Field label="角色"><select value={role} onChange={e=>setRole(e.target.value as AppRole)}>{Object.entries(roleLabels).filter(([id])=>id!=='super_admin').map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></Field><p>{roleDescriptions[role]}</p><Field label="访问状态"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="active">正常</option><option value="disabled">停用 Web Radar 访问</option></select></Field><p className="muted">权限修改立即用于后续请求。停用账号不会删除历史数据。</p><div className="modal-actions"><Button onClick={()=>setEdit(null)}>取消</Button><Button kind="primary" busy={busy} onClick={save}>保存权限</Button></div></Modal>}
    {detail&&<Modal title="业务明细（最近 100 条）" onClose={()=>setDetail(null)} wide><div className="table-scroll"><table><thead><tr>{detail.columns.map((x:string)=><th key={x}>{x}</th>)}</tr></thead><tbody>{detail.rows.map((row:any[],i:number)=><tr key={i}>{row.map((v:any,j:number)=><td key={j}>{v==null?'—':String(v)}</td>)}</tr>)}</tbody></table></div></Modal>}
  </div>;
}
